Problem: C Compilation fails in a few cases with global constants.
Project constant definition:
```
  <constant name = "global constant stuff" value = "123" type = "string" >
    this is a
    multi-line comment
    for global constant
  </constant>

```

Generated header file:
```
    this is a
    multi-line comment
    for global constant
```

Compilation failure:
```
make[1]: Entering directory `/home/cbox_dev/git/zproject-issues-testing'
  CC       src/src_libfbp_la-foo.lo
In file included from src/../include/libfoobar.h:18:0,
                 from src/fbp_classes.h:35,
                 from src/foo.c:21:
src/../include/fbp_library.h:95:5: error: unknown type name 'this'
     this is a
     ^
src/../include/fbp_library.h:95:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'a'
     this is a
             ^
...
```

See #1291 for more details.

Solution: Apply a similar fix than #1283, but on global constants.
```
// this is a
// multi-line comment
// for global constant
```

Additionnally, a few blank lines are added to separate the constants
definitions, from each other.

Note:
Global constants should be prefixed with `$(PROJECT.PREFIX:c)_`,
like for version constants, but this is not applied here.